# Generated by Django 5.2 on 2026-05-12 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(choices=[('corte', 'Corte de Cabelo'), ('barba', 'Barba'), ('corte_barba', 'Corte + Barba'), ('hidratacao', 'Hidratação Capilar'), ('sobrancelha', 'Sobrancelha')], max_length=20)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='chatbot.cliente')),
            ],
            options={
                'unique_together': {('data', 'horario')},
            },
        ),
    ]
