# Generated by Django 5.2 on 2026-05-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50, unique=True)),
                ('dados', models.JSONField(default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
